name: Send Daily Screenshot

on:
  schedule:
    - cron: "00 21 * * *" # 23:00 Berlin time => 21:00 UTC
  workflow_dispatch:

jobs:
  send-screenshot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 22

      - run: npm install

      - run: npx playwright install --with-deps

      - run: node index.js
        env:
          STATS_HUNTERS_SHARE_URL: ${{ vars.STATS_HUNTERS_SHARE_URL }}
          SMTP_HOST: ${{ vars.SMTP_HOST }}
          SMTP_PORT: ${{ vars.SMTP_PORT }}
          SMTP_USER: ${{ vars.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          RECEIVER_MAIL: ${{ vars.RECEIVER_MAIL }}

      - name: Upload trace as artifact
        uses: actions/upload-artifact@v4
        with:
          name: trace
          path: trace.zip

      - name: Upload screenshot as artifact
        uses: actions/upload-artifact@v4
        with:
          name: daily-activity-screenshot
          path: images/daily-activity.png
